"""
Central configuration for the Deep-Sea Creature Detection & Classification System.
All paths, model parameters, thresholds, and class mappings are defined here.
"""

import os
import torch
from pathlib import Path

# ──────────────────────────────────────────────
# Project root (directory containing this file)
# ──────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).parent.resolve()

# ──────────────────────────────────────────────
# Device configuration (auto-detect GPU)
# ──────────────────────────────────────────────
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ──────────────────────────────────────────────
# Dataset paths
# ──────────────────────────────────────────────
DATA_DIR = PROJECT_ROOT / "data"
DATA_YAML = DATA_DIR / "data.yaml"

# Classifier crop dataset (generated by prepare_classifier_data.py)
CLASSIFIER_DATA_DIR = PROJECT_ROOT / "classifier_data"

# ──────────────────────────────────────────────
# Model paths
# ──────────────────────────────────────────────
MODELS_DIR = PROJECT_ROOT / "models"

# YOLOv8 model weights
YOLO_N_WEIGHTS = MODELS_DIR / "yolov8n_aquarium" / "weights" / "best.pt"
YOLO_S_WEIGHTS = MODELS_DIR / "yolov8s_aquarium" / "weights" / "best.pt"

# Species classifier
CLASSIFIER_WEIGHTS = MODELS_DIR / "classifier" / "best_classifier.pth"
CLASSIFIER_CLASS_NAMES = MODELS_DIR / "classifier" / "class_names.json"

# ──────────────────────────────────────────────
# Roboflow dataset settings
# ──────────────────────────────────────────────
ROBOFLOW_WORKSPACE = "brad-dwyer"
ROBOFLOW_PROJECT = "aquarium-combined"
ROBOFLOW_VERSION = 2
ROBOFLOW_FORMAT = "yolov8"

# ──────────────────────────────────────────────
# Class names (Aquarium Combined dataset)
# ──────────────────────────────────────────────
CLASS_NAMES = [
    "fish",
    "jellyfish",
    "penguin",
    "puffin",
    "shark",
    "starfish",
    "stingray",
]
NUM_CLASSES = len(CLASS_NAMES)

# ──────────────────────────────────────────────
# YOLO detection parameters
# ──────────────────────────────────────────────
YOLO_CONF_THRESHOLD = 0.25       # Minimum confidence for raw detections
YOLO_IOU_THRESHOLD = 0.45        # NMS IoU threshold within each model
YOLO_IMG_SIZE = 640              # Input image size for YOLO

# ──────────────────────────────────────────────
# Human-review gate
# ──────────────────────────────────────────────
# Minimum confidence for a fused box to be trusted. Boxes below this are
# discarded after fusion; if none survive, the image is flagged for review.
#
# Judged per box rather than on the mean across all boxes. Detections enter the
# pool from YOLO_CONF_THRESHOLD (0.25) upward, so a crowded scene accumulates a
# long tail of marginal boxes. Averaging over that tail let weak detections veto
# strong ones and rejected busier images the hardest — the opposite of intended.
REVIEW_CONF_THRESHOLD = 0.40

# Laplacian variance below which an image is unreadable and no detection from it
# can be trusted, however confident the detector claims to be. Separate from
# REVIEW_CONF_THRESHOLD: that one asks "did we find anything?", this one asks
# "was there enough image to find it in?".
#
# Calibrated against measured blur variance: unusable frames score 0.7-1.0, the
# softest genuine sample scores 89.4, and the validation set's 1st percentile is
# 4.4. Distinct from the far more permissive is_blurry check (< 100.0), which
# only decides whether to apply a sharpening filter.
UNUSABLE_BLUR_THRESHOLD = 5.0

# ──────────────────────────────────────────────
# YOLO training parameters
# ──────────────────────────────────────────────
YOLO_TRAIN_EPOCHS = 50
YOLO_TRAIN_BATCH = 16
YOLO_TRAIN_IMGSZ = 640
YOLO_TRAIN_PATIENCE = 15         # Early stopping patience

# Model A (nano) — default augmentations
YOLO_N_SEED = 42
YOLO_N_AUGMENT = {
    "mosaic": 1.0,
    "mixup": 0.0,
    "copy_paste": 0.0,
}

# Model B (small) — enhanced augmentations for diversity
YOLO_S_SEED = 123
YOLO_S_AUGMENT = {
    "mosaic": 1.0,
    "mixup": 0.15,
    "copy_paste": 0.1,
}

# ──────────────────────────────────────────────
# Weighted Boxes Fusion (WBF) parameters
# ──────────────────────────────────────────────
WBF_IOU_THRESHOLD = 0.55         # IoU threshold for clustering boxes
WBF_SKIP_BOX_THRESHOLD = 0.001   # Discard boxes below this confidence
WBF_WEIGHTS = [2, 1]             # [yolov8n weight, yolov8s weight]
WBF_CONF_TYPE = "avg"            # Confidence fusion method

# ──────────────────────────────────────────────
# Species classifier parameters
# ──────────────────────────────────────────────
CLASSIFIER_IMG_SIZE = 224
CLASSIFIER_BACKBONE = "resnet18"

# ImageNet normalization stats
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

# ──────────────────────────────────────────────
# Classifier training parameters
# ──────────────────────────────────────────────
CLASSIFIER_TRAIN_EPOCHS = 25
CLASSIFIER_TRAIN_BATCH = 32
CLASSIFIER_TRAIN_LR = 1e-3
CLASSIFIER_FREEZE_EPOCHS = 10    # Freeze early layers for this many epochs

# ──────────────────────────────────────────────
# Crop extraction parameters
# ──────────────────────────────────────────────
CROP_PADDING = 0.10              # 10% padding around bounding box crops

# ──────────────────────────────────────────────
# Combined confidence scoring
# ──────────────────────────────────────────────
DETECTOR_WEIGHT = 0.6            # Weight for detector confidence
CLASSIFIER_WEIGHT = 0.4          # Weight for classifier confidence
AGREEMENT_BOOST = 0.10           # Boost when detector & classifier agree

# ──────────────────────────────────────────────
# Annotation drawing parameters
# ──────────────────────────────────────────────
ANNOTATION_FONT_SCALE = 0.6
ANNOTATION_THICKNESS = 2
ANNOTATION_COLORS = {
    "high":   (0, 200, 83),      # Green  — confidence >= 0.75
    "medium": (0, 191, 255),     # Cyan   — confidence >= 0.50
    "low":    (0, 100, 255),     # Orange — confidence < 0.50
}

def get_confidence_color(confidence: float) -> tuple:
    """Return BGR color based on confidence level."""
    if confidence >= 0.75:
        return ANNOTATION_COLORS["high"]
    elif confidence >= 0.50:
        return ANNOTATION_COLORS["medium"]
    else:
        return ANNOTATION_COLORS["low"]

# ──────────────────────────────────────────────
# Saved prediction outputs
# ──────────────────────────────────────────────
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

# ──────────────────────────────────────────────
# API configuration
# ──────────────────────────────────────────────
API_HOST = "0.0.0.0"
API_PORT = 8000
ALLOWED_IMAGE_TYPES = {"image/jpeg", "image/png", "image/jpg", "image/webp"}
MAX_IMAGE_SIZE_MB = 20
